import type { GridOptions } from "../types/GridOptions"

export const defaultOptions: GridOptions = {
	t: "─",
	ti: "┴",
	b: "─",
	bi: "┬",
	l: "│",
	li: "┤",
	r: "│",
	ri: "├",
	tl: "┌",
	tr: "┐",
	br: "┘",
	bl: "└",
	i: "┼",
	fill: "\u{0A0}",
	sl: "█",
	sr: "█",
	st: "█",
	sb: "█",
	debug: false,
	font: "'Cascadia Mono', 'Courier New', Courier, monospace",
	fontPath: "https://raw.githubusercontent.com/zachariahwatson/html-to-ascii/main/CascadiaMono.woff",
	fontSize: 18,
	fontWeight: 400,
}
